config/routes.rb
Rails.application.routes.draw do
  resources :questions, except: [:edit, :update, :destroy] do
    resources :answers, only: [:create]
    resources :comments, only: [:create]
    resource :vote, only: [:create, :destroy]
  end
  resources :answers, only: [:index] do
    resources :comments, only: [:create]
    resource :vote, only: [:create, :destroy]
  end
  get 'questions/:id/answers', to: 'questions#show'
  get 'questions/:id/comments', to: 'questions#show'
  get 'answers/:id/comments', to: 'questions#show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'questions#index'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  body        :text
#  user_id     :integer
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def voted_by?(user)
    votes.exists?(user: user)
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  commentable_type :string
#  commentable_id   :integer
#  text             :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :text, presence: true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :title, :description, presence: true

  def self.search(search)
    where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%") 
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :questions
  has_many :answers
  has_many :votes
  has_many :comments

  validates :email, :password, presence: true
  validates :email, uniqueness: true
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  votable_type :string
#  votable_id   :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
    @question = Question.find(params[:question_id])
    answer = @question.answers.new(answer_params)
    @answers = @question.answers
    if answer.save
      redirect_to(@question)
    else
      @errors = answer.errors.full_messages
      render 'questions/show'
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:body).merge(user: current_user, question_id: params[:question_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    comment.user = current_user
    if params[:question_id]
      @question = Question.find(params[:question_id])
      @answers = @question.answers
      @comment = Comment.new
      if @question.comments << comment
        redirect_to(@question)
      else
        @errors = comment.errors.full_messages
        render 'questions/show'
      end
    else
      answer = Answer.find(params[:answer_id])
      @question = Question.find(answer.question_id)
      @answers = @question.answers
      @comment = Comment.new
      if answer.comments << comment
        redirect_to(@question)
      else
        @errors = comment.errors.full_messages
        render 'questions/show'
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show]

  def index
    if params[:search]
      @questions = Question.search(params[:search])
    else
      @questions = Question.all
    end
  end

  def show
    @answers = @question.answers
    @comment = Comment.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to(root_path, notice: 'Pregunta publicada con éxito')
    else
      render :new
    end
  end

  private
    def question_params
      params.require(:question).permit(:title, :description)
    end

    def find_question
      @question = Question.find(params[:id])
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if params[:question_id]
      question = Question.find(params[:question_id])
      question.votes.create(user: current_user)
    else
      answer = Answer.find(params[:answer_id])
      question = Question.find(answer.question_id)
      answer.votes.create(user: current_user)
    end
    redirect_to(question)
  end

  def destroy
    if params[:question_id]
      question = Question.find(params[:question_id])
      question.votes.where(user: current_user).take.try(:destroy)
    else
      answer = Answer.find(params[:answer_id])
      question = Question.find(answer.question_id)
      answer.votes.where(user: current_user).take.try(:destroy)
    end
    redirect_to(question)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, no_intra_emphasis: true, fenced_code_blocks: true, disable_indented_code_blocks: true)
    return markdown.render(text).html_safe
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  
    def devise_error_messages!
      flash_alerts = []
      error_key = 'errors.messages.not_saved'
  
      if !flash.empty?
        flash_alerts.push(flash[:error]) if flash[:error]
        flash_alerts.push(flash[:alert]) if flash[:alert]
        flash_alerts.push(flash[:notice]) if flash[:notice]
        error_key = 'devise.failure.invalid'
      end
  
      return "" if resource.errors.empty? && flash_alerts.empty?
      errors = resource.errors.empty? ? flash_alerts : resource.errors.full_messages
  
      messages = errors.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t(error_key, :count    => errors.count,
                                   :resource => resource.class.model_name.human.downcase)
  
      html = <<-HTML
      <div class="alert alert-danger">
        <div id="error_explanation">
          <h2>#{sentence}</h2>
          <ul>#{messages}</ul>
        </div>
      </div>
      HTML
  
      html.html_safe
    end
  
  end

app/helpers/questions_helper.rb
module QuestionsHelper
  def form_title
    @question.new_record? ? 'Publicar Pregunta' : 'Modificar Pregunta'
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowOverstack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-inverse container-fluid">
      <div class="container-fluid">
        <div class="container">
          <div class="navbar-header">
            <%= link_to  "FlowOverstack", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to  "Salir", destroy_user_session_path, method: 'delete' %></li>
            <% else %>
              <li><%= link_to  "Ingresar", new_user_session_path %></li>
              <li><%= link_to  "Registrarse", new_user_registration_path %></li>
            <% end %>
            <li>
              <%= form_tag(questions_path, :method => "get", id: "search-form", class: "navbar-form") do %>
                  <div class="form-group">
                    <%= text_field_tag :search, params[:search], placeholder: "Buscar pregunta", class: "form-control" %>
                  </div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <% if flash[:notice] %>
    <div class="container">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <div class="alert alert-info">
              <%= flash[:notice] %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1><%= form_title %></h1>

      <% if @question.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @question.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_for @question do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Título" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class: "form-control input-lg", placeholder: "Descripción" %>
        </div>
        <div>
          <%= f.submit form_title, class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="questions">
        <h1>Preguntas</h1>
        
        <% if @questions.blank? %>
          <div class="alert alert-info">
            <h4>No hay preguntas que contengan el término <%= params[:search] %>.</h4>
          </div>
        <% end %>
        
        <div class="new-question">
          <% if user_signed_in? %>
            <%= link_to  "Hacer una Pregunta", new_question_path, class: "btn btn-primary pull-right" %>
          <% end %>
        </div>
        
        <table class="table">
          <tbody>
            <% @questions.each do |question| %>
              <tr>
                <td class="text-center">
                  <h3><span><%= question.votes.count %></span></h3>
                  <p>Votos</hp
                </td>
                <td class="text-center">
                  <h3><span><%= question.answers.count %></span></h3>
                  <p>Respuestas</p>
                </td>
                <td>
                  <h3><%= link_to  question.title, question %></h3>
                  <p>Preguntó <%= question.user.email %> hace <%= time_ago_in_words(question.created_at) %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<%= render  "form" %>

app/views/questions/show.html.erb
<% if @errors %>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="alert alert-info">
          <ul>
            <% @errors.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="questions">
        <h1><%= @question.title %></h1>
        <table class="table">
          <tbody>
            <tr>
              <td class="text-center">
                <% if user_signed_in? %>
                  <% if @question.voted_by?(current_user) %>
                    <%= link_to  question_vote_path(@question), method: :delete, class: "upvote upvote-voted" do %>
                      <span class="vote-counter-lk"><%= @question.votes.count %></span><br>
                      <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                    <% end %>
                  <% else %>
                    <%= link_to  question_vote_path(@question), method: :post, class: "upvote" do %>
                      <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span><br>
                      <span class="vote-counter-lk"><%= @question.votes.count %></span>
                    <% end %>
                  <% end %>
                <% else %>
                  <span class="vote-counter"><%= @question.votes.count %></span>
                <% end %>
              </td>
              <td>
                <p><%= markdown(@question.description) %></p>
              </td>
            </tr>            
          </tbody>
        </table>

        <div class="comments">
          <h3>Commentarios</h3>

          <table class="table">
            <tbody>
              <% @question.comments.each do |comment| %>
                <tr>
                  <td>
                    <header class="panel-heading">
                      <h4><%= comment.user.email %> comentó hace <% if !comment.text.blank? %><%= time_ago_in_words(comment.created_at) %><% end %></h4>
                    </header>
                    <div class="panel-body">
                      <p><%= comment.text %></p>
                    </div>
                  </td>
                </tr>
              <% end %>
                
              <% if user_signed_in? %>
                <tr>
                  <td>
                    <%= form_for [@question, @comment] do |f| %>
                      <div class="form-group">
                        <%= f.text_area :text, class: "form-control", placeholder: "Agrega un comentario" %>
                      </div>
                      <div class="actions text-right">
                        <%= f.submit "Comentar", class: "btn btn-primary" %>
                      </div>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>


      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="answers">
        <% if @answers.blank? %>
          <h2>0 Respuesta(s)</h2>
        <% else %>
          <h2><%= @answers.count %> Respuesta(s)</h2>
        <% end %>
        
        <table class="table">
          <tbody>
            <% @answers.each do |answer| %>
              <tr>
                <td class="text-center">
                  
                  <% if user_signed_in? %>
                    <% if answer.voted_by?(current_user) %>
                      <%= link_to  answer_vote_path(answer), method: :delete, class: "upvote upvote-voted" do %>
                        <span class="vote-counter-lk"><%= answer.votes.count %></span><br>
                        <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
                      <% end %>
                    <% else %>
                      <%= link_to  answer_vote_path(answer), method: :post, class: "upvote" do %>
                        <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span><br>
                        <span class="vote-counter-lk"><%= answer.votes.count %></span>
                      <% end %>
                    <% end %>
                  <% else %>
                    <span class="vote-counter"><%= answer.votes.count %></span>
                  <% end %>
                </td>
                <td>
                  <p><%= markdown(answer.body) %></p>
                </td>
              </tr>
              <div class="comments">
                <tr class="text-right">
                  <td></td>
                  <td>
                    <h3>Commentarios</h3>
                  </td>
                </tr>
                
                <% answer.comments.each do |comment| %>
                  <tr>
                    <td></td>
                    <td>
                      <header class="panel-heading">
                        <h4><%= comment.user.email %> comentó hace <%= time_ago_in_words(comment.created_at) %></h4>
                      </header>
                      <div class="panel-body">
                        <p><%= comment.text %></p>
                      </div>
                    </td>
                  </tr>
                <% end %>

                <% if user_signed_in? %>
                  <tr>
                    <td></td>
                    <td>
                      <%= form_for [answer, @comment] do |f| %>
                        <div class="form-group">
                          <%= f.text_area :text, class: "form-control", placeholder: "Agrega un comentario" %>
                        </div>
                        <div class="actions text-right">
                          <%= f.submit "Comentar", class: "btn btn-primary" %>
                        </div>
                      <% end %>
                    </td>
                  </tr>
                <% end %>

              </div>
            <% end %>
          </tbody>
        </table>

        <% if user_signed_in? %>

          <h2>Tu Respuesta</h2>
          <%= form_for [@question, @question.answers.build] do |f| %>
            <div class="form-group">
              <%= f.text_area :body, class: "form-control" %>
            </div>
            <div class="actions text-right">
                <%= f.submit "Responder", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>